changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: 🚀 Features
      labels:
        - feat
        - feature
        - enhancement
    - title: 🐛 Bug fixes
      labels:
        - fix
        - bug
    - title: 📝 Documentation
      labels:
        - docs
        - documentation
    - title: ⚡ Performance
      labels:
        - perf
        - performance
    - title: ♻️ Refactors
      labels:
        - refactor
    - title: 🧹 Maintenance
      labels:
        - chore
        - build
        - ci
    - title: Other changes
      labels:
        - "*"
