package infrastructure

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	domain "github.com/mptooling/notifycat/internal/routing/domain"
)

// LockPath derives the lock-file path that lives next to the given
// mappings.yaml. .yaml / .yml extensions are swapped for .lock; any other
// suffix gets .lock appended.
func LockPath(yamlPath string) string {
	ext := filepath.Ext(yamlPath)
	switch strings.ToLower(ext) {
	case ".yaml", ".yml":
		return yamlPath[:len(yamlPath)-len(ext)] + ".lock"
	default:
		return yamlPath + ".lock"
	}
}

// LockFileComment is the human-facing warning baked into every written lock.
const LockFileComment = "DO NOT EDIT — regenerated by notifycat on validation"

// LockVersion is the current lock-file schema version.
const LockVersion = 1

// Lock is the on-disk validation cache.
type Lock struct {
	Comment string               `json:"_comment,omitempty"`
	Version int                  `json:"version"`
	Entries map[string]LockEntry `json:"entries"`
}

// LockEntry records the hash and validation timestamp for one entry.
type LockEntry struct {
	SHA256      string    `json:"sha256"`
	ValidatedAt time.Time `json:"validated_at"`
}

// Diff is the result of DiffEntries: entries needing validation + lock keys
// that should be dropped on the next write.
type Diff struct {
	Needs []domain.Entry
	Stale []string
}

// ReadLock parses path. A missing file returns an empty Lock with no error.
// A malformed file returns an empty Lock and an error so the caller can warn
// and continue.
func ReadLock(path string) (Lock, error) {
	b, err := os.ReadFile(path) //nolint:gosec // path is operator-supplied configuration
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return Lock{Version: LockVersion, Entries: map[string]LockEntry{}}, nil
		}
		return Lock{Entries: map[string]LockEntry{}}, fmt.Errorf("mappings: read lock %s: %w", path, err)
	}
	var l Lock
	if err := json.Unmarshal(b, &l); err != nil {
		return Lock{Entries: map[string]LockEntry{}}, fmt.Errorf("mappings: parse lock %s: %w", path, err)
	}
	if l.Entries == nil {
		l.Entries = map[string]LockEntry{}
	}
	return l, nil
}

// WriteLock writes the lock atomically (write to tmp + rename).
func WriteLock(path string, l Lock) error {
	l.Comment = LockFileComment
	l.Version = LockVersion
	b, err := json.MarshalIndent(l, "", "  ")
	if err != nil {
		return fmt.Errorf("mappings: marshal lock: %w", err)
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, b, 0o600); err != nil {
		return fmt.Errorf("mappings: write lock tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("mappings: rename lock: %w", err)
	}
	return nil
}

// DiffEntries compares the current entries against the lock and returns
// which entries need validation (new or hash-changed) and which lock keys
// are stale (present in the lock but not in the file).
func DiffEntries(current []domain.Entry, lock Lock) Diff {
	currentKeys := make(map[string]struct{}, len(current))
	var needs []domain.Entry
	for _, e := range current {
		key := e.Key()
		currentKeys[key] = struct{}{}
		prior, ok := lock.Entries[key]
		if !ok || prior.SHA256 != e.Hash() {
			needs = append(needs, e)
		}
	}
	var stale []string
	for k := range lock.Entries {
		if _, ok := currentKeys[k]; !ok {
			stale = append(stale, k)
		}
	}
	return Diff{Needs: needs, Stale: stale}
}

// MergeLock returns a new Lock built from `old` by adding the `validated`
// entries and dropping the keys in `drop`.
func MergeLock(old Lock, validated map[string]LockEntry, drop []string) Lock {
	out := Lock{Version: LockVersion, Entries: map[string]LockEntry{}}
	for k, v := range old.Entries {
		out.Entries[k] = v
	}
	for _, k := range drop {
		delete(out.Entries, k)
	}
	for k, v := range validated {
		out.Entries[k] = v
	}
	return out
}
